spring:
  application:
    name: serviceRegistry
  cloud:
    config:
      importCheck:
        enabled: false
server:
  port: 8325
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49