spring:
  application:
    name: serviceDiscovery
server:
  port: 8325
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enableSelfPreservation: false