spring:
  application:
    name: loadBalancer
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: true
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20