spring:
  application:
    name: loadBalancer
  cloud:
    discovery:
      enabled: true
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka/
  instance:
    preferIpAddress: true
