spring:
  application:
    name: loadBalancer
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true