spring:
  application:
    name: loadBalancer
  web:
   resources:
     static-locations:
       - classpath:/static/
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka/
