spring:
  application:
    name: userstorageapp-service
  redis:
    host: localhost
    port: 6379
  cloud:
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true
server:
  port: ${SERVER_PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20