spring:
  application:
    name: nodeStorageApp-service
server:
  port: ${SERVER_PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8325/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    preferIpAddress: true